homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.index, name="index"),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models
import datetime

# Create your models here.

class response(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, blank=True)

homepage/forms.py
from django import forms

from .models import response

class ResponseForm(forms.ModelForm):
    class Meta:
        model = response
        fields = [
            'status',
        ]

homepage/views.py
from django.shortcuts import render
from .forms import ResponseForm
from .models import response

# Create your views here.

def index(request):
    form = ResponseForm(request.POST or None)
    responses = response.objects.all()
    if form.is_valid():
        form.save()
        form = ResponseForm()
    context = {
        'form' : form,
        'respon' : responses,
    }

    return render(request, 'index.html', context)

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Landing Page</title>
</head>
<body>
    <div class="row">
        <div class="col-12 mt-3 mb-5">
            <h1 class="display-3 font-weight-bold title">Mind.</h1>
        </div>
        <div class="col-6 text-center">
            <img class="rounded-circle img-thumbnail" src="{% static 'img/portrait.jpg' %}"" alt="">
        </div>
        <div class="col-6 text-center">
            <h4 class="font-weight-bold">Halo,<br>apa kabar?</h4>
            <div class="container mt-3 mb-1">
                <form action="{% url 'homepage:index' %}" method="post">
                    {% csrf_token %}
                    {% for item in form %}
                    {{item}}
                    {% endfor %}
                    <br>
                    <button type="submit" class="btn btn-outline-secondary mt-3">Submit</button>
                </form>
            </div>
        </div>
        {% for item in respon %}
        <div class="col-12">
            <div class="container">
                <h4 class="text-break font-weight-bold mt-3 mb-3">{{item.status}}</h4>
                <p>{{item.date}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>